import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/components/ClientProvider";


export const metadata: Metadata = {
  title: "Paige",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
      <body
        className={`bg-bgcolor text-primary `}
        >
        {children}
      </body>
        </ClientProvider>
    </html>
  );
}
