export const jobs = [
    {
      id: 1,
      title: "Frontend Developer",
      category: "Tech",
      company: "Amazon",
    },
    {
      id: 2,
      title: "Nurse",
      category: "Healthcare",
      company: "Google",
    },
    {
      id: 3,
      title: "Accountant",
      category: "Finance",
      company: "Access Bank.",
    },
    {
      id: 4,
      title: "Teacher",
      category: "Education",
      company: "Bright Future Academy",
    },
    {
      id: 5,
      title: "Backend Developer",
      category: "Tech",
      company: "Facebook",
    },
    {
      id: 6,
      title: "Dataa Analyst",
      category: "Finance",
      company: "Shopify",
    },
    {
      id: 7,
      title: "Vet Doctor",
      category: "Healthcare",
      company: "HealWell Clinic",
    },
    {
      id: 8,
      title: "Lecturer",
      category: "Education",
      company: "Uni Lag",
    },
    {
      id: 1,
      title: "Frontend Developer",
      category: "Tech",
      company: "Amazon",
    },
    {
      id: 2,
      title: "Nurse",
      category: "Healthcare",
      company: "Google",
    },
    {
      id: 3,
      title: "Accountant",
      category: "Finance",
      company: "Access Bank.",
    },
    {
      id: 4,
      title: "Teacher",
      category: "Education",
      company: "Bright Future Academy",
    },
    {
      id: 5,
      title: "Backend Developer",
      category: "Tech",
      company: "Facebook",
    },
    {
      id: 6,
      title: "Dataa Analyst",
      category: "Finance",
      company: "Shopify",
    },
    {
      id: 7,
      title: "Vet Doctor",
      category: "Healthcare",
      company: "HealWell Clinic",
    },
    {
      id: 8,
      title: "Lecturer",
      category: "Education",
      company: "Uni Lag",
    },
    {
      id: 1,
      title: "Frontend Developer",
      category: "Tech",
      company: "Amazon",
    },
    {
      id: 2,
      title: "Nurse",
      category: "Healthcare",
      company: "Google",
    },
    {
      id: 3,
      title: "Accountant",
      category: "Finance",
      company: "Access Bank.",
    },
    {
      id: 4,
      title: "Teacher",
      category: "Education",
      company: "Bright Future Academy",
    },
    {
      id: 5,
      title: "Backend Developer",
      category: "Tech",
      company: "Facebook",
    },
    {
      id: 6,
      title: "Dataa Analyst",
      category: "Finance",
      company: "Shopify",
    },
    {
      id: 7,
      title: "Vet Doctor",
      category: "Healthcare",
      company: "HealWell Clinic",
    },
    {
      id: 8,
      title: "Lecturer",
      category: "Education",
      company: "Uni Lag",
    },
    {
      id: 1,
      title: "Frontend Developer",
      category: "Tech",
      company: "Amazon",
    },
    {
      id: 2,
      title: "Nurse",
      category: "Healthcare",
      company: "Google",
    },
    {
      id: 3,
      title: "Accountant",
      category: "Finance",
      company: "Access Bank.",
    },
    {
      id: 4,
      title: "Teacher",
      category: "Education",
      company: "Bright Future Academy",
    },
    {
      id: 5,
      title: "Backend Developer",
      category: "Tech",
      company: "Facebook",
    },
    {
      id: 6,
      title: "Dataa Analyst",
      category: "Finance",
      company: "Shopify",
    },
    {
      id: 7,
      title: "Vet Doctor",
      category: "Healthcare",
      company: "HealWell Clinic",
    },
    {
      id: 8,
      title: "Lecturer",
      category: "Education",
      company: "Uni Lag",
    },
    {
      id: 1,
      title: "Frontend Developer",
      category: "Tech",
      company: "Amazon",
    },
    {
      id: 2,
      title: "Nurse",
      category: "Healthcare",
      company: "Google",
    },
    {
      id: 3,
      title: "Accountant",
      category: "Finance",
      company: "Access Bank.",
    },
    {
      id: 4,
      title: "Teacher",
      category: "Education",
      company: "Bright Future Academy",
    },
    {
      id: 5,
      title: "Backend Developer",
      category: "Tech",
      company: "Facebook",
    },
    {
      id: 6,
      title: "Dataa Analyst",
      category: "Finance",
      company: "Shopify",
    },
    {
      id: 7,
      title: "Vet Doctor",
      category: "Healthcare",
      company: "HealWell Clinic",
    },
    {
      id: 8,
      title: "Lecturer",
      category: "Education",
      company: "Uni Lag",
    },
    {
      id: 1,
      title: "Frontend Developer",
      category: "Tech",
      company: "Amazon",
    },
    {
      id: 2,
      title: "Nurse",
      category: "Healthcare",
      company: "Google",
    },
    {
      id: 3,
      title: "Accountant",
      category: "Finance",
      company: "Access Bank.",
    },
    {
      id: 4,
      title: "Teacher",
      category: "Education",
      company: "Bright Future Academy",
    },
    {
      id: 5,
      title: "Backend Developer",
      category: "Tech",
      company: "Facebook",
    },
    {
      id: 6,
      title: "Dataa Analyst",
      category: "Finance",
      company: "Shopify",
    },
    {
      id: 7,
      title: "Vet Doctor",
      category: "Healthcare",
      company: "HealWell Clinic",
    },
    {
      id: 8,
      title: "Lecturer",
      category: "Education",
      company: "Uni Lag",
    },
    {
      id: 1,
      title: "Frontend Developer",
      category: "Tech",
      company: "Amazon",
    },
    {
      id: 2,
      title: "Nurse",
      category: "Healthcare",
      company: "Google",
    },
    {
      id: 3,
      title: "Accountant",
      category: "Finance",
      company: "Access Bank.",
    },
    {
      id: 4,
      title: "Teacher",
      category: "Education",
      company: "Bright Future Academy",
    },
    {
      id: 5,
      title: "Backend Developer",
      category: "Tech",
      company: "Facebook",
    },
    {
      id: 6,
      title: "Dataa Analyst",
      category: "Finance",
      company: "Shopify",
    },
    {
      id: 7,
      title: "Vet Doctor",
      category: "Healthcare",
      company: "HealWell Clinic",
    },
    {
      id: 8,
      title: "Lecturer",
      category: "Education",
      company: "Uni Lag",
    },
  ];